# Every workflow .yml file needs to have three things. Workflow means cicd pipeline 
# 1. on(A trigger- Event,i.e. push, pull, merge) , 2. jobs - job-id(Job identifier) 3. runs-on (a remote machine where workflow runs on)
name: Deploys website to S3+CloudFront
on:
  workflow-dispatch:

jobs:
  deploys:
    runs-on: ubuntu-latest

    steps:
    # this step is mandatory to add in almost all workflow
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v5.1.1
        with:
          aws-region: ${{secrets.AWS_REGION}}
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          
      - name: Deploy website to S3
        run: |
          aws s3 sync website/ s3://${{secrets.S3_BUCKET_NAME}} --delete 
    # here --delete flag make sure that destination deletes all the files that source doen't have

      - name: Invalidate cloudfront cache
        run: |
          aws cloudfront create-invalidation \
          --distribution-id ${{secrets.CLOUDFRONT_DISTRIBUTION_ID}} \
          --paths "/*"
            
        